version: "2"
sql:
  - engine: "sqlite"
    schema: "../internal/db/schema/migrations"
    queries: "../internal/db/schema/queries"
    gen:
      go: 
        package: "db"
        out: "../internal/db/"

