// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: daily_report_data.sql

package db

import (
	"context"
)

const findStatistics = `-- name: FindStatistics :many
select date, pending, category, holiday, hours, minutes from daily_report_data where date = ?1
`

func (q *Queries) FindStatistics(ctx context.Context, date int64) ([]DailyReportDatum, error) {
	rows, err := q.db.QueryContext(ctx, findStatistics, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyReportDatum
	for rows.Next() {
		var i DailyReportDatum
		if err := rows.Scan(
			&i.Date,
			&i.Pending,
			&i.Category,
			&i.Holiday,
			&i.Hours,
			&i.Minutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
