name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Display Go version
        run: go version
      - name: Tidy up
        run: go mod tidy
      - uses: sqlc-dev/setup-sqlc@v4
        timeout-minutes: 5
        with:
          sqlc-version: '1.25.0'
      - run: sqlc version
      - name: Run tests
        timeout-minutes: 5
        run: make tests
      - name: Run vet
        timeout-minutes: 10
        run: go vet ./...
      - name: golangci-lint
        timeout-minutes: 5
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.4
          args: ./...
